--CREATE CUSTOMER VIEW

CREATE VIEW DIM_CUSTOMER_V AS
(
SELECT DIMCUSTOMERID, DIMLOCATIONID, CUSTOMERID, CUSTOMERFULLNAME, CUSTOMERFIRSTNAME, CUSTOMERLASTNAME, CUSTOMERGENDER
FROM DIM_CUSTOMER  
);

--CREATE RESELLER VIEW

CREATE VIEW DIM_RESELLER_V AS
(
SELECT DIMRESELLERID, DIMLOCATIONID, RESELLERID, RESELLERNAME, CONTACTNAME, PHONENUMBER, EMAIL
FROM DIM_RESELLER
);

--CREATE LOCATION VIEW
CREATE VIEW DIM_LOCATION_V AS
(
SELECT DIMLOCATIONID, ADDRESS, CITY, POSTALCODE, STATE_PROVINCE, COUNTRY
FROM DIM_LOCATION 
);

--BONUS SHARE VIEW Q2

CREATE OR REPLACE VIEW BONUS_SHARE_V AS
(
SELECT YEAR, STORENUMBER,PROFIT, SALE,
SUM(SALE) OVER (PARTITION BY YEAR) AS TOTAL_SALE,
ROUND((SALE/TOTAL_SALE),2) AS PROPORTION,
ROUND
(
CASE WHEN YEAR = 2013 THEN 500000*(SALE/TOTAL_SALE)
    WHEN YEAR = 2014 THEN 400000*(SALE/TOTAL_SALE)
END,2) AS BONUS_PROPORTION
FROM
(
SELECT D.Year, S.STORENUMBER,
SUM(FSA.SALEAMOUNT) AS SALE, 
SUM(FSA.SALETOTALPROFIT) AS PROFIT
FROM FACT_SALESACTUAL FSA
INNER JOIN DIM_STORE S ON FSA.DIMSTOREID = S.DIMSTOREID
INNER JOIN DIM_PRODUCT P ON FSA.DIMPRODUCTID = P.DIMPRODUCTID
INNER JOIN DIM_DATE D ON FSA.DIMSALEDATEID = D.DATE_PKEY
WHERE P.PRODUCTTYPE LIKE '%Casual' AND STORENUMBER IN (5,8)
AND D.YEAR || D.MONTH_NUM_IN_YEAR NOT IN (201411, 201412) --These  months are in Date table but not in our fact tables 
GROUP BY D.Year, S.STORENUMBER
)
ORDER BY YEAR, STORENUMBER
);


--PRODUCT SALES VIEW Q3
CREATE OR REPLACE VIEW PRODUCT_SALES_V AS
(SELECT D.YEAR, S.STORENUMBER, D.DAY_NAME,
AVG(FSA.SALEAMOUNT) AS AVG_SALESAMT,
SUM(FSA.SALEQUANTITY) AS QUANTITY,
SUM(FSA.SALEAMOUNT) AS SALE,
SUM(FSA.SALETOTALPROFIT) AS PROFIT
 
FROM FACT_SALESACTUAL AS FSA
INNER JOIN DIM_STORE AS S ON FSA.DIMSTOREID = S.DIMSTOREID
INNER JOIN DIM_DATE AS D ON D.DATE_PKEY = FSA.DIMSALEDATEID
INNER JOIN DIM_PRODUCT AS P ON P.DIMPRODUCTID = FSA.DIMPRODUCTID
 
WHERE S.STORENUMBER IN (5,8)
GROUP BY D.YEAR, FSA.DIMSTOREID, D.DAY_NAME, S.STORENUMBER
ORDER BY D.YEAR, FSA.DIMSTOREID, AVG_SALESAMT DESC);

-- STATEWISE PERFORMACE VIEW Q4 
CREATE OR REPLACE VIEW STATEWISE_PERFORMANCE_V AS
(SELECT D.YEAR, D.MONTH_NAME, L.STATE_PROVINCE, A.CNT_STORE,
AVG(FSA.SALEAMOUNT) AS AVG_SALESAMT,
SUM(FSA.SALEQUANTITY) AS QUANTITY,
SUM(FSA.SALEAMOUNT) AS SALE,
SUM(FSA.SALETOTALPROFIT) AS PROFIT
 
FROM FACT_SALESACTUAL AS FSA
INNER JOIN DIM_STORE AS S ON FSA.DIMSTOREID = S.DIMSTOREID
INNER JOIN DIM_DATE AS D ON D.DATE_PKEY = FSA.DIMSALEDATEID
INNER JOIN DIM_LOCATION AS L ON S.DIMLOCATIONID = L.DIMLOCATIONID
INNER JOIN DIM_PRODUCT AS P ON FSA.DIMPRODUCTID = P.DIMPRODUCTID
INNER JOIN
(
SELECT L.STATE_PROVINCE, COUNT(S.STORENUMBER) AS CNT_STORE
FROM DIM_STORE AS S
    